version: '3.8'

# Docker Compose file for testing Docker Hub images locally
# Use this to test your builds before pushing to Docker Hub

services:
  # Test the main CUDA-compatible image
  chatterbox-tts-main:
    build:
      context: .
      dockerfile: docker/Dockerfile.dockerhub
    container_name: chatterbox-tts-main
    ports:
      - '5123:5123'
    environment:
      # API Configuration
      - PORT=5123
      - HOST=0.0.0.0

      # TTS Model Settings (can be overridden)
      - EXAGGERATION=${EXAGGERATION:-0.5}
      - CFG_WEIGHT=${CFG_WEIGHT:-0.5}
      - TEMPERATURE=${TEMPERATURE:-0.8}

      # Device auto-detection (works for both GPU and CPU)
      - DEVICE=auto

    volumes:
      # Mount voice sample (users can override this)
      - ${VOICE_SAMPLE_HOST_PATH:-./voice-sample.mp3}:/app/voice-sample.mp3:ro

      # Mount model cache for persistence
      - chatterbox-models:/cache

      # Optional: Mount custom voice samples directory
      - ${VOICE_SAMPLES_DIR:-./voice-samples}:/app/voice-samples:ro

    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5123/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s

  # Test the CPU-only image
  chatterbox-tts-cpu:
    build:
      context: .
      dockerfile: docker/Dockerfile.dockerhub.cpu
    container_name: chatterbox-tts-cpu
    ports:
      - '5124:5123' # Different port to avoid conflicts
    environment:
      - PORT=5123
      - HOST=0.0.0.0
      - EXAGGERATION=${EXAGGERATION:-0.5}
      - CFG_WEIGHT=${CFG_WEIGHT:-0.5}
      - TEMPERATURE=${TEMPERATURE:-0.8}
      - DEVICE=cpu # Force CPU for this variant

    volumes:
      - ${VOICE_SAMPLE_HOST_PATH:-./voice-sample.mp3}:/app/voice-sample.mp3:ro
      - chatterbox-models-cpu:/cache
      - ${VOICE_SAMPLES_DIR:-./voice-samples}:/app/voice-samples:ro

    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5123/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s

volumes:
  chatterbox-models:
    driver: local
  chatterbox-models-cpu:
    driver: local
