[project]
name = "chatterbox-tts-api"
version = "1.0.0"
description = "REST API for Chatterbox TTS with OpenAI compatibility"
authors = [{ name = "Travis Van Nimwegen", email = "tts@travis2.com" }]
readme = "README.md"
license = { text = "AGPLv3" }
requires-python = ">=3.11"
dependencies = [
  "chatterbox-tts @ git+https://github.com/resemble-ai/chatterbox.git",
  "torch>=2.0.0,<2.7.0",
  "torchaudio>=2.0.0,<2.7.0",
  "flask>=2.3.0",
  "python-dotenv>=1.0.0",
  "requests>=2.28.0",
]

[project.urls]
Homepage = "https://github.com/travisvn/chatterbox-tts-api"
Repository = "https://github.com/travisvn/chatterbox-tts-api"

[project.optional-dependencies]
dev = [
  "requests>=2.28.0", # for testing
]

# PyTorch index configuration for different accelerators
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

# Source configuration with environment markers for cross-platform support
# Removed custom CUDA indexes - let PyTorch auto-detect CUDA from runtime
[tool.uv.sources]
# torch and torchaudio will use default PyPI, which should auto-detect CUDA
# from the CUDA runtime environment in Docker

[tool.uv]
dev-dependencies = ["requests>=2.28.0"]
